.github/workflows/retrain.yml

Simula el Mantenimiento Continuo (Re-entrenamiento programado)

name: 锔 Mantenimiento Continuo (CM) - Re-entrenamiento Mensual

on:

Disparador principal: Ejecuci贸n programada (cron)

Ejecuta el d铆a 1 de cada mes a las 00:00 UTC (ajusta seg煤n tu necesidad)

schedule:
- cron: '0 0 1 * *'

Permite la ejecuci贸n manual desde la interfaz de GitHub

workflow_dispatch:

jobs:
retrain_and_validate:
runs-on: ubuntu-latest

steps:
- name: 1. Obtener Repositorio
  uses: actions/checkout@v4

- name: 2. Configurar Python 3.10
  uses: actions/setup-python@v5
  with:
    python-version: '3.10'

- name: 3. Instalar Dependencias (Incluyendo LightGBM)
  run: |
    pip install --upgrade pip
    pip install -r requirements.txt
    pip install scikit-learn pandas

- name: 4. Crear Estructura de Carpetas (Necesario para el script)
  run: |
    mkdir -p data
    mkdir -p models
    # En un escenario real, aqu铆 se descargar铆a el 煤ltimo dataset
    # Por ahora, copiamos el archivo base para la simulaci贸n:
    cp MTA_Bus_Metrics_2024.csv data/MTA_Bus_Metrics_2024.csv
    
# Paso CLAVE: Ejecuta el script que entrena y valida.
- name: 5. Ejecutar Script de Re-entrenamiento y Validaci贸n
  # El script guardar谩 el modelo solo si es mejor.
  run: python scripts/retrain.py

# 6. Si se promocion贸 un nuevo modelo (los archivos .pkl han cambiado),
# disparamos el pipeline de CI/CD para desplegar la nueva versi贸n.
- name: 6. Despliegue de Nuevo Modelo a Producci贸n (CI/CD)
  if: success() 
  run: |
    # Esto simular铆a la subida de los nuevos artefactos.
    # En un entorno real, aqu铆 se llamar铆a al workflow de despliegue.
    echo " Se detect贸 un nuevo modelo. Disparando el Pipeline de Despliegue (CI/CD)..."
    # Para el prop贸sito de esta demostraci贸n, este echo es suficiente.
    # Si quisieras disparar el otro workflow, usar铆as:
    # gh workflow run ci-cd.yml -f message='Nuevo modelo entrenado'
  env:
    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
